import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const exists = p => fs.existsSync(path.join(root,p));
const failures = [];
const checks = [];
function assert(name, ok, detail=''){
  checks.push({name,ok,detail});
  if(!ok) failures.push(name + (detail ? ': '+detail : ''));
}

const required = [
  'public/index.html','public/manifest.webmanifest','public/sw.js',
  'public/privacy.html','public/terms.html','public/release-100-v1.css','public/nataiji-final-visual-v1.css','public/nataiji-premium-v2.css','public/nataiji-premium-v2.js','public/nataiji-home-reference-v1.css','public/nataiji-home-reference-v1.js',
  'public/nataiji-brand-mark.png','capacitor.config.ts',
  '.github/workflows/mobile-android-release.yml',
  '.github/workflows/mobile-ios-appstore.yml',
  '.github/workflows/mobile-production-smoke.yml',
  'scripts/server-smoke.mjs'
];
for (const file of required) assert('required:'+file, exists(file));

const index = read('public/index.html');
const sw = read('public/sw.js');
const server = read('src/server.js');
const appJs = read('public/app.js');
const capacitor = read('capacitor.config.ts');
const pkg = JSON.parse(read('package.json'));
const lockPkg = JSON.parse(read('package-lock.json'));
const manifest = JSON.parse(read('public/manifest.webmanifest'));
assert('RC package version', pkg.version === '1.0.0-rc.1');
assert('lockfile matches RC package version', lockPkg.version === pkg.version && lockPkg.packages?.['']?.version === pkg.version);
assert('PWA stable app identity', manifest.id === '/' && manifest.name === 'نتائجي | Nataiji' && manifest.display === 'standalone');
assert('release freeze document exists', exists('RELEASE.md') && /Nataiji v1\.0\.0 RC1/.test(read('RELEASE.md')));
assert('Android RC version is wired from package.json', /Apply RC version metadata/.test(read('.github/workflows/mobile-android-release.yml')) && /versionCode 1/.test(read('.github/workflows/mobile-android-release.yml')));
assert('iOS RC version metadata is explicit', /Apply RC version metadata/.test(read('.github/workflows/mobile-ios-appstore.yml')) && /CURRENT_PROJECT_VERSION = 1/.test(read('.github/workflows/mobile-ios-appstore.yml')));
const directDownload = read('.github/workflows/mobile-download.yml');
const downloadPage = read('public/download.html');
assert('direct Android download uses RC version metadata', /Apply RC version metadata/.test(directDownload) && /versionCode 1/.test(directDownload));
assert('direct Android package remains installable APK', /assembleDebug/.test(directDownload) && /app-debug\.apk/.test(directDownload));
assert('official download page identifies RC1 and Android sideloading', /Nataiji v1\.0\.0 RC1/.test(downloadPage) && /خارج Google Play/.test(downloadPage));
assert('download page links privacy and terms', /\/privacy\.html/.test(downloadPage) && /\/terms\.html/.test(downloadPage));

assert('brand title', /نتائجي\s*\|\s*Nataiji/.test(index));
assert('viewport safe area', /viewport-fit=cover/.test(index));
assert('rtl-ltr boot direction', /document\.documentElement\.dir/.test(index));
assert('final mobile css loaded', /release-100-v1\.css/.test(index));
assert('final visual polish loaded', /nataiji-final-visual-v1\.css/.test(index));
assert('premium v2 visual layer loaded', /nataiji-premium-v2\.css/.test(index) && /nataiji-premium-v2\.js/.test(index));
assert('approved home reference layer loaded last', /nataiji-home-reference-v1\.css/.test(index) && /nataiji-home-reference-v1\.js/.test(index));
assert('privacy page exists', exists('public/privacy.html'));
assert('terms page exists', exists('public/terms.html'));
assert('PWA cache version current', /nataiji-shell-v94/.test(sw));
assert('PWA caches final mobile css', /release-100-v1\.css/.test(sw));
assert('PWA caches final visual polish', /nataiji-final-visual-v1\.css/.test(sw));
assert('PWA caches premium v2 layer', /nataiji-premium-v2\.css/.test(sw) && /nataiji-premium-v2\.js/.test(sw));
assert('PWA caches approved home reference layer', /nataiji-home-reference-v1\.css/.test(sw) && /nataiji-home-reference-v1\.js/.test(sw));
assert('PWA excludes API cache', /pathname\.startsWith\("\/api\/"\)/.test(sw));
assert('auth copy avoids ambiguous temporary storage', !/وضع تخزين مؤقت|Mode de stockage temporaire/.test(read('public/auth-access-v2.js')));
assert('French auth direction is explicit', /lang-fr \.auth-gate/.test(read('public/auth-access-v2.js')) || /lang-fr \.auth-gate/.test(read('public/interface-language-fix.js')));
const authAccess = read('public/auth-access-v2.js');
assert('auth exposes Arabic French language switch', /data-auth-lang="ar"/.test(authAccess) && /data-auth-lang="fr"/.test(authAccess));
assert('auth language switch updates direction immediately', /document\.documentElement\.dir=next==='fr'\?'ltr':'rtl'/.test(authAccess));
const bilingualEditor = read('public/bilingual-data-editor-v1.js');
assert('paired Arabic French fields sync live both ways', /const fromAr=\(\)=>/.test(bilingualEditor) && /f\.value=arToFr\(a\.value\)/.test(bilingualEditor) && /const fromFr=\(\)=>/.test(bilingualEditor) && /a\.value=frToAr\(f\.value\)/.test(bilingualEditor) && /a\.addEventListener\('input'.*fromAr\(\)/.test(bilingualEditor) && /f\.addEventListener\('input'.*fromFr\(\)/.test(bilingualEditor));
assert('new subject starts with blank bilingual names and max score', /draft\.push\(\['',1,'','',''\]\)/.test(bilingualEditor));
const adminUxPolish = read('public/admin-ux-polish-v1.js');
assert('new blank subject opens immediately', /const isNew=!String\(ar\?\.value\|\|''\)\.trim\(\)/.test(adminUxPolish));
assert('subject header uses compact edit delete guide', /السهم لفتح المادة وتعديلها/.test(bilingualEditor) && /لحذف المادة/.test(bilingualEditor) && !/المعامل ثابت/.test(bilingualEditor));
const structureManager = read('public/structure-manager.js');
const annualResults = read('public/annual-results-v1.js');
const twoA4 = read('public/two-students-a4-v1.js');
assert('third trimester annual average uses 1-2-3 weighting', /return \(avgs\[0\]\+2\*avgs\[1\]\+3\*avgs\[2\]\)\/6/.test(annualResults) && /\(\(a1\?\?0\)\+2\*\(a2\?\?0\)\+3\*\(a3\?\?0\)\)\/6/.test(twoA4));
assert('third trimester rank uses annual average', /const vals=\(state\?\.pupils\|\|\[\]\)\.map\(\(_,i\)=>\{const v=annualAverage\(i\)/.test(annualResults) && /annualRank=third\?annualRankData\.ranks\[i\]/.test(twoA4));
assert('third trimester bulletin keeps earlier-term results', /A pupil who has any positive result in T1\/T2\/T3 must keep their bulletin/.test(appJs) && /if\(isThird\(s\)\)\{const annual=annualFor\(s,i\);return annual!=null&&Number\(annual\)>0\}/.test(twoA4));
assert('school structure uses exactly three fixed trimesters', /const FIXED_TERMS=\['الفصل الأول','الفصل الثاني','الفصل الثالث'\]/.test(structureManager) && !/id="addTerm"/.test(structureManager) && !/data-term-del/.test(structureManager));
assert('structure modal localizes trimesters and standard classes', /TERM_FR/.test(structureManager) && /CLASS_FR/.test(structureManager) && /Trimestres et classes/.test(structureManager));
const onboarding = read('public/onboarding-v1.js');
assert('school form uses precise French school label', /Nom de l’école en français/.test(authAccess) && /Nom de l’école en français/.test(onboarding) && /Nom de l’école en français/.test(bilingualEditor));
assert('My Schools keeps Arabic and French school names synchronized', /schoolAr\.addEventListener\('input'.*schoolFr\.value=toFr/s.test(authAccess) && /schoolFr\.addEventListener\('input'.*schoolAr\.value=toAr/s.test(authAccess));
assert('school create action is full width', /#auth2AddSchool\{width:100%!important/.test(adminUxPolish));
assert('teacher invite labels grade access clearly', /الوصول إلى الدرجات/.test(authAccess) && /اختر «تعديل» أمام المواد/.test(authAccess));
assert('teacher invite warns when no subject is editable', /لم تمنح المعلم تعديل أي مادة/.test(adminUxPolish) && /اختر «تعديل» أمام مادة واحدة على الأقل/.test(adminUxPolish));
assert('teacher invite permissions are compact on mobile', /\.auth2-invite \.auth2-perms label\{margin:0!important;padding:6px 4px!important/.test(adminUxPolish));
const interfaceLanguage = read('public/interface-language-fix.js');
assert('institution academic year stays LTR', /id="by" class="bi-year-input" dir="ltr"/.test(bilingualEditor) && /\.bi-year-input\{direction:ltr!important/.test(bilingualEditor));
assert('institution AR FR marker is a compact badge', /bi-title-badge/.test(bilingualEditor) && /بيانات المؤسسة<\/span><span class="bi-title-badge"/.test(bilingualEditor));
assert('language card has only one icon source', !/<svg viewBox="0 0 24 24"[^>]*aria-hidden="true"[^>]*focusable="false"/.test(interfaceLanguage) && /langSwitch:'globe'/.test(read('public/luxury-ui-v1.js')));
assert('shared class attach action is full width', /\.auth2-join-modal \.action\{width:100%!important/.test(adminUxPolish));
const morePageJs = read('public/more-page-v1.js');
const morePageCss = read('public/more-page-v1.css');
assert('More page is grouped without moving cards out of settings grid', /GROUPS=\[/.test(morePageJs) && /Compte et école/.test(morePageJs) && /Paramètres académiques/.test(morePageJs) && /Collaboration et partage/.test(morePageJs));
assert('More page keeps cards compact for mobile', /\.nataiji-more-grid>\.menu-card\.more-row-card/.test(morePageCss) && /@media\(max-width:390px\)/.test(morePageCss));
assert('More page preserves RTL LTR chevron direction', /inset-inline-end:17px/.test(morePageCss) && /\.lang-fr \.nataiji-more-grid>\.menu-card\.more-row-card:after\{content:"›"\}/.test(morePageCss));
assert('More page assets are loaded', /more-page-v1\.css\?v=4/.test(index) && /more-page-v1\.js\?v=6/.test(index));
assert('legacy danger reorder yields to grouped More page', /grid\.classList\.contains\('nataiji-more-grid'\)/.test(read('public/app-power-v1.js')));
assert('account danger actions stay in account group', /termsPolicyBtn','logoutBtn','deleteAccountBtn'/.test(morePageJs));
assert('account management is the last More page section', /key:'academic'[\s\S]*key:'collaboration'[\s\S]*key:'account'/.test(morePageJs));
assert('language card keeps a single globe icon', /card\.id==='langSwitch'/.test(morePageJs) && /icon\.dataset\.feather='globe'/.test(morePageJs));
assert('More page leaves room above bottom navigation', /padding-bottom:calc\(140px \+ env\(safe-area-inset-bottom,0px\)\)/.test(morePageCss));
assert('dashboard shows provisional average before completion', /partialAvgs=state\.pupils\.map/.test(appJs) && /مؤقت حسب الدرجات المدخلة/.test(appJs));
assert('dashboard below-ten count uses entered marks provisionally', /needsEl\.textContent=finalAvgs\.length\?finalAvgs\.filter\(x=>x<10\)\.length:'—'/.test(appJs));
const appPowerJs = read('public/app-power-v1.js');
assert('More page exposes app share action', /id='shareAppBtn'/.test(appPowerJs) && /navigator\.share/.test(appPowerJs));
assert('install action hides after app installation', /isAppInstalled/.test(appPowerJs) && /appinstalled/.test(appPowerJs));
assert('share/install cards do not rewrite after feather rendering', /dataset\.uiLang===uiLang/.test(appPowerJs) && !/b\.innerHTML!==html/.test(appPowerJs));
assert('install and share precede support', /installAppBtn','shareAppBtn','supportBtn'/.test(morePageJs));
assert('Super Admin card overrides generic More row styling', /menu-card\.owner-card\.more-row-card/.test(morePageCss) && /background:linear-gradient\(120deg,#071f38/.test(morePageCss));
assert('subject save requires explicit maximum score', /الدرجة القصوى/.test(bilingualEditor) && /bi-field-invalid/.test(bilingualEditor) && /data-sm/.test(bilingualEditor));
assert('focused invalid subject fields remain red', /input\.bi-field-invalid:focus/.test(bilingualEditor));
assert('subject validation summarizes all missing fields', /أكمل الحقول المطلوبة/.test(bilingualEditor) && /الاسم بالعربية/.test(bilingualEditor) && /الاسم بالفرنسية/.test(bilingualEditor) && /الدرجة القصوى/.test(bilingualEditor));
assert('all report print actions are primary green', /#printResult,[\s\S]*\.report-print\{[\s\S]*color:#fff!important[\s\S]*background:linear-gradient\(135deg,#078b70,#086f61\)!important/.test(read('public/nataiji-premium-v2.css')));
const reportEnhancements = read('public/report-enhancements.js');
const printDocuments = read('public/print-documents.js');
assert('zero-result pupil cannot print individual report', /zeroResultPupil/.test(appJs) && /type==='student'/.test(appJs) && /مجموعه ومعدله صفر/.test(appJs));
assert('zero-result pupils are excluded from batch reports', /allOptions=\[\.\.\.s\.options\]/.test(reportEnhancements) && /sum===0&&Number\(c\?\.avg\)===0/.test(reportEnhancements));
assert('zero-result pupils stay in class result list as absent', /absent=Number\(c\?\.sum\)===0&&Number\(c\?\.avg\)===0/.test(printDocuments) && /absent\?'غائب'/.test(printDocuments));
assert('install card has no legacy text glyph', !/[⬇↓↔]/u.test(read('public/app-power-v1.js')));
const appPower = read('public/app-power-v1.js');
assert('More menu ordering avoids mutation loop', /del&&del!==grid\.lastElementChild/.test(appPower) && /logout&&logout\.nextElementSibling!==del/.test(appPower));
assert('dynamic sharing cards use canonical icons', /data-feather=\"share-2\"/.test(read('public/auth-access-v2.js')) && /data-feather=\"link\"/.test(read('public/auth-access-v2.js')));
assert('grade enhancer scoped to real grade inputs', /input\.mark\[data-i\]\[data-j\],input\.mobile-mark\[data-i\]\[data-j\]/.test(read('public/final-grade-entry.js')));
assert('absence button exposes explicit selected state', /aria-pressed/.test(read('public/final-grade-entry.js')) && /aria-pressed/.test(read('public/grade-mobile-ui-v1.js')));
const gradeMobileUi = read('public/grade-mobile-ui-v1.js');
assert('grade entry renders current subject icon host', /grade-current-subject-icon/.test(gradeMobileUi));
assert('grade entry keeps inactive absence control visually neutral until selected', /border:1px solid #d8e1e8/.test(gradeMobileUi) && /background:#fff!important;color:#667784/.test(gradeMobileUi) && /absent-btn::before/.test(gradeMobileUi) && /is-absent \.absent-btn\{background:#f2b51d/.test(gradeMobileUi));
assert('grade entry compacts filters and rows', /padding:11px!important;border-radius:15px/.test(gradeMobileUi) && /height:58px!important;min-height:58px!important;max-height:58px/.test(gradeMobileUi));
assert('bulk grade save persists validated values', /normalizedMarks/.test(server));
assert('manual grade save flushes autosave queue', /await markCellSaveTail\.catch/.test(appJs) && /pendingGradeSaves\.get\(key\)/.test(appJs));
assert('manual grade save does not bulk-overwrite marks', !/\$\('#saveGrades'\)[\s\S]{0,2200}api\('\/api\/marks'/.test(appJs));
const professorV2 = read('public/professor-v2.js');
const professorV2Css = read('public/professor-v2.css');
const professorCatalogSrc = read('src/professor-academic-catalog.js');
assert('official Mauritanian professor catalog is wired', /MR-SECONDARY-OFFICIAL-2026-V4/.test(professorCatalogSrc) && /code:'7AS'/.test(professorCatalogSrc) && /technology_informatics/.test(professorCatalogSrc) && /branch\('A',29/.test(professorCatalogSrc) && /branch\('C',30/.test(professorCatalogSrc));
assert('collective professor list uses official subject abbreviations', /name\.abbr\|\|String\(s\.subjectKey/.test(professorV2) && /<b dir="ltr">\$\{esc\(abbr\)\}<\/b>/.test(professorV2));
assert('collective subject headers use vertical Arabic labels', /professorCollectiveSubjectArabic/.test(professorV2) && /subject-vertical/.test(professorV2) && /writing-mode:vertical-rl/.test(professorV2));
assert('collective vertical Arabic subject labels are enlarged', /subject-vertical\{height:30mm[^}]*font-size:9\.2pt/.test(professorV2));
assert('collective list is ranked and readable on Android print', /function professorClassListLandscape\(\)\{return false\}/.test(professorV2) && /orderedStudents=/.test(professorV2) && /collective-class-table/.test(professorV2));
assert('collective list omits class average footer', !/class=\"summary\"><div class=\"dual-summary\"/.test(professorV2.slice(professorV2.indexOf('function printClassList'),professorV2.indexOf('function professorReportSwitcher'))));
assert('collective metadata is arranged in bilingual rows', /collective-meta-row ar/.test(professorV2) && /collective-meta-row fr/.test(professorV2) && /مجموع المعاملات:/.test(professorV2));
assert('collective signatures are enlarged', /class-list-doc \.official-signatures b\{font-size:11pt/.test(professorV2) && /official-date-line span\{font-size:9\.3pt/.test(professorV2));
assert('collective PDF uses numeric ranks and no stamp box', /class-list-students-few/.test(professorV2) && /studentCount:data\.students\?\.length\|\|0/.test(professorV2) && !/الختم \/ Cachet/.test(professorV2) && /التوقيع \/ Signature/.test(professorV2));
assert('collective professor results include every official curriculum subject', /const officialSubjects=orderedSubjects\.map/.test(server) && /assigned:false,marks:\{\}/.test(server) && /officialCoefficientTotal=subjects\.reduce/.test(server) && /Math\.abs\(officialCoefficientTotal-expectedCoefficientTotal\)/.test(server));
assert('linked professor marks use canonical shared class metadata', /canonicalLevelCode/.test(server) && /canonicalBranchCode/.test(server) && /mergeMarks=/.test(server));
assert('collective official results are not labelled provisional', /if\(data\?\.curriculumComplete&&data\?\.expectedCoefficientTotal\)return String\(data\.expectedCoefficientTotal\)/.test(professorV2) && /officialReady=general!=null&&curriculumComplete/.test(server));
assert('professor grades use dedicated verified save endpoint', professorV2.includes("'/students/'+encodeURIComponent(row.studentId)+'/grades'") && /r\.verified!==true/.test(professorV2) && /professor_grade_verification_failed/.test(server));
assert('structural professor save flushes pending grades first', /async function saveProfile\(message=''\)\{\s*if\(gradeSaveTimer\|\|gradeSaveInFlight\|\|gradeSavedRevision<gradeEditRevision\)await flushGradeAutosave\(\)/.test(professorV2));
assert('professor recovery snapshots retain 200 versions', /ORDER BY id DESC LIMIT 200/.test(server));
assert('professor grades have append-only server history', /nataiji_professor_grade_history/.test(server) && /appendProfessorGradeHistory/.test(server));
assert('structural professor saves preserve surviving grades', /function preserveProfessorMarks\(/.test(server) && /candidate=preserveProfessorMarks\(before,req\.body\?\.profile\)/.test(server));
assert('opening professor profile never rewrites stored grades', /profile=cleanProfessorProfile\(profile\);\s*res\.json\(\{ok:true,profile,classLinks\}\)/.test(server) && !/profile=cleanProfessorProfile\(profile\);await saveProfessorProfile\(req\.user\.id,profile,\{syncShared:false\}\)/.test(server));
assert('manual professor save verifies every student atomically', /async function forceProfessorGradeSave\(\)/.test(professorV2) && /students\/'\+encodeURIComponent\(row\.studentId\)\+'\/grades/.test(professorV2) && /before-student-grade-save/.test(server) && /professor_grade_reload_verification_failed/.test(professorV2));
assert('manual professor save commits every visible grade input before request', /const commitVisibleGradeInputs=\(\)=>/.test(professorV2) && /commitVisibleGradeInputs\(\);gradeEditRevision\+\+/.test(professorV2));
assert('professor absence is independent and counts as zero', /data-absent-kind="test"/.test(professorV2) && /data-absent-kind="exam"/.test(professorV2) && /if\(professorIsAbsent\(v\)\)return 0/.test(professorV2) && /if\(professorResultAbsent\(v\)\)return 0/.test(server));
assert('professor grade entry uses class and subject selectors', /id="pv2GradeClassSelect"/.test(professorV2) && /id="pv2GradeSubjectSelect"/.test(professorV2) && /const next=assignmentsForClass\(value\)\[0\]/.test(professorV2));
assert('professor grade selectors include quick add actions', /value="__add_class__"/.test(professorV2) && /value="__add_subject__"/.test(professorV2) && /openAssignment\('','new'\)/.test(professorV2) && /openAssignment\(a\.classId,'existing'\)/.test(professorV2));
assert('professor quick add returns to new subject grade entry', /gradeMatch=.*\^grade:/.test(professorV2) && /openGrades\(newAssignment\.id,Number\(gradeMatch\[1\]\)\)/.test(professorV2));
assert('shared professor classes are explicitly labelled in selector', /مشترك · /.test(professorV2) && /Partagée · /.test(professorV2));
assert('professor full absence displays absent while calculation stays zero', /function professorTermFullyAbsent/.test(professorV2) && /professorTermFullyAbsent\(m,term\)\?tr\('غائب','Absent'\)/.test(professorV2) && /if\(professorIsAbsent\(v\)\)return 0/.test(professorV2));
assert('fully absent students stay only in collective list', /function professorStudentFullyAbsent/.test(professorV2) && /allRows\.filter\(row=>!professorStudentFullyAbsent\(row\)\)/.test(professorV2) && /const orderedStudents=\[\.\.\.\(data\.students\|\|\[\]\)\]/.test(professorV2));
assert('individual professor bulletin blocks fully absent student', /if\(professorStudentFullyAbsent\(row\)\)\{toast/.test(professorV2));
assert('professor compact grade table is scoped to professor workspace', /prof-grade-compact-table/.test(professorV2) && /\.nataiji-professor-mode \.prof-grade-reference \.prof-grade-compact-table/.test(professorV2Css));
assert('professor compact grade entry keeps verified save path', /forceProfessorGradeSave\(\)/.test(professorV2) && /professor_grade_reload_verification_failed/.test(professorV2));
assert('professor assignment dialog separates existing and new class flows', /data-assignment-mode="existing"/.test(professorV2) && /data-assignment-mode="new"/.test(professorV2) && /id="pv2ExistingClassLabel"/.test(professorV2) && /id="pv2NewClassLabel"/.test(professorV2));
assert('official professor coefficient field is hidden unless manual', /id="pv2CoefficientLabel" style="display:none"/.test(professorV2) && /coefLabel\.style\.display=manual\?'grid':'none'/.test(professorV2));
assert('professor shared class badge is explicit on grades page', /prof-shared-class-badge/.test(professorV2) && /tr\('مشترك','Partagée'\)/.test(professorV2));
assert('official professor coefficient stays automatic and manual coefficient is custom-only', /if\(spec\?\.official\)\{coef\.value=spec\.coefficient;coef\.readOnly=true/.test(professorV2) && /const .*manual=subjectSel\.value==='__other__'\|\|\(subjectSel\.value&&!spec\?\.official\)/.test(professorV2) && /coefLabel\.style\.display=manual\?'grid':'none'/.test(professorV2));
assert('professor grade cards are compact with grade entry as primary action', /prof-compact-subject-card/.test(professorV2) && /primary-card-action/.test(professorV2) && /Professor workflow simplification v47/.test(professorV2Css));
assert('professor reports remove duplicate collective entry and term icons', /prof-report-switcher-premium/.test(professorV2) && !/prof-collective-entry prof-collective-entry-premium/.test(professorV2.slice(professorV2.indexOf('function renderReportsHub'),professorV2.indexOf('async function renderResults'))) && !/data-own-report-term="\$\{t\}"[^>]*><span/.test(professorV2));
assert('collective PDF uses compact values and compact absence labels', /function compactResultText/.test(professorV2) && /class="collective-absent"/.test(professorV2) && /td class="subject-value"/.test(professorV2));

assert('professor absence stays labelled in documents', /if\(professorIsAbsent\(v\)\)return professorAbsentLabel\(student\)/.test(professorV2) && /professorReportTermAverage/.test(professorV2));
assert('professor own lists refresh from server before display', /async function openMySubjectsList[\s\S]{0,240}await refreshProfile\(\)/.test(professorV2) && /async function openSubjectList[\s\S]{0,240}await refreshProfile\(\)/.test(professorV2));
assert('professor PDF avoids visible about blank window', !/window\.open\('',\s*'_blank'\)/.test(professorV2) && /document\.createElement\('iframe'\)/.test(professorV2) && /contentWindow\?\.print/.test(professorV2));
assert('professor official bulletin prints one student per A4 page', /official-student-bulletin-doc/.test(professorV2) && /singlePages:true/.test(professorV2) && /class=\"student-page\"/.test(professorV2) && /Observations du Directeur/.test(professorV2));
assert('official bulletin enlarges header and student identity', /official-student-bulletin-doc \.official-head\{[^}]*font-size:10\.8pt/.test(professorV2) && /official-student-bulletin-doc \.student-name\{[^}]*font-size:12\.2pt/.test(professorV2));
assert('student bulletin rebalances columns for readability', /test-head/.test(professorV2) && /test-cell/.test(professorV2) && /obs-head,.official-student-bulletin-doc \.secondary-bulletin-table \.observation-cell\{width:25%\}/.test(professorV2) && /discipline-head\{width:28%\}/.test(professorV2));
assert('student bulletin text is enlarged throughout', /secondary-bulletin-table\{font-size:9\.5pt/.test(professorV2) && /td:not\(\.name\):not\(\.observation-cell\)\{font-size:10\.1pt/.test(professorV2) && /observation-cell \.dual-ar\{display:block;font-size:9\.3pt/.test(professorV2));
assert('student bulletin decision and signatures are easy to read', /official-bulletin-summary b\{display:block;font-size:9\.2pt/.test(professorV2) && /official-bulletin-summary strong\{display:block;font-size:12\.2pt/.test(professorV2) && /official-student-bulletin-doc \.official-signatures b\{font-size:9\.5pt/.test(professorV2));
assert('bulletin summary has more vertical space', /official-bulletin-summary>div\{min-height:14mm/.test(professorV2));
assert('Arabic official header is balanced against French', /official-student-bulletin-doc \.official-ar\{font-size:11\.7pt/.test(professorV2) && /class-list-doc \.official-ar\{font-size:11\.5pt/.test(professorV2));
assert('professor batch bulletin label says one student per A4', /كشوف التلاميذ الرسمية – طالب واحد لكل A4/.test(professorV2) && /Bulletins officiels – 1 élève par A4/.test(professorV2));
assert('professor v2 cache-busted asset is current', /professor-v2\.js\?v=68/.test(index));
assert('professor v2 stylesheet cache-busted asset is current', /professor-v2\.css\?v=47/.test(index));
const ownerStaff = read('public/owner-staff-v1.js');
assert('owner professor tools support official branches', /staffClassBranch/.test(ownerStaff) && /data-branch/.test(ownerStaff) && /subjectOptions\(catalog,level,branch\)/.test(ownerStaff));
assert('owner staff cache-busted asset is current', /owner-staff-v1\.js\?v=3/.test(index));
assert('secure cookie enabled', /httpOnly:true/.test(server) && /sameSite:'lax'/.test(server));
assert('origin protection enabled', /cross_site_request_blocked/.test(server));
assert('CSP enabled', /Content-Security-Policy/.test(server));
assert('HSTS enabled', /Strict-Transport-Security/.test(server));
assert('password hashing is scrypt', /scryptSync/.test(server));
assert('account password change exists', /\/api\/account\/password/.test(server));
assert('account deletion exists', /app\.delete\('\/api\/account'/.test(server));
assert('health endpoint exists', /app\.get\('\/health'/.test(server));
assert('durable storage health reporting', /storage/.test(server) && /databaseOk/.test(server));
assert('Capacitor package id', /appId:\s*'mr\.nataiji\.app'/.test(capacitor));
assert('Capacitor HTTPS production url', /https:\/\/nataiji\.onrender\.com/.test(capacitor));
assert('Android dependency present', Boolean(pkg.dependencies?.['@capacitor/android']));
assert('iOS dependency present', Boolean(pkg.dependencies?.['@capacitor/ios']));

const css = read('public/release-100-v1.css');
const premiumV2 = read('public/nataiji-premium-v2.css');
const subjectLocale = read('public/premium-subject-locale-v1.js');
const homeReference = read('public/nataiji-home-reference-v1.css');
assert('home CTA normal-flow guard', /welcome button[\s\S]*position:static!important/.test(css));
assert('subject wrapping guard', /subject-progress-name[\s\S]*word-break:normal!important/.test(css));
assert('mobile report controls guard', /report-tabs[\s\S]*grid-template-columns:repeat\(3/.test(css));
assert('safe-area bottom nav', /safe-area-inset-bottom/.test(css));
assert('premium v2 is screen-scoped and print-safe', /@media screen/.test(premiumV2) && /@media print/.test(premiumV2));
assert('premium v2 keeps official report content untouched', !/official-sheet[^\n]*display:none/.test(premiumV2));
assert('semantic subject icon set present', /islamic:/.test(subjectLocale) && /arabic:/.test(subjectLocale) && /math:/.test(subjectLocale) && /civic:/.test(subjectLocale) && /art:/.test(subjectLocale) && /french:/.test(subjectLocale) && /sport:/.test(subjectLocale));
assert('premium icon helper deduplicates direct icons', /direct\.slice\(1\)\.forEach/.test(read('public/nataiji-premium-v2.js')));
assert('home reference is screen-only and report-safe', /@media screen/.test(homeReference) && !/official-sheet|report-preview-stage|data-page=\"reports\"/.test(homeReference));
assert('home reference compacts progress list', /#subjectProgress>div/.test(homeReference) && /np-home-show-all/.test(homeReference));

console.log('\nNataiji final release audit');
for (const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${c.detail?' — '+c.detail:''}`);
if (failures.length){
  console.error(`\n${failures.length} release gate check(s) failed.`);
  process.exit(1);
}
console.log(`\nAll ${checks.length} release gate checks passed.`);
